[project]
name = 'DecentraFund'
description = 'Decentralized Crowdfunding Platform'
authors = []
telemetry = false
cache_dir = '.cache'

[contracts]
ft-token-trait = { path = 'contracts/ft-token-trait.clar' }
reward-token = { path = 'contracts/reward-token.clar' }
escrow = { path = 'contracts/escrow.clar' }
crowdfunding = { path = 'contracts/crowdfunding.clar' }

[repl]
cost_limit = 5000