[project]
name = 'DecentraFund'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'
requirements = []
[contracts.crowdfunding]
path = 'contracts/crowdfunding.clar'
clarity_version = 1
epoch = 2.05

[contracts.escrow]
path = 'contracts/escrow.clar'
clarity_version = 3
epoch = 3.1

[contracts.reward-token]
path = 'contracts/reward-token.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
