[project]
name = "DecentraFund"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.contributors]
path = "contracts/contributors.clar"
depends_on = []

[contracts.crowdfunding]
path = "contracts/crowdfunding.clar"
depends_on = []

[contracts.tokens]
path = "contracts/tokens.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
